kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8sdc-operator
subjects:
- kind: ServiceAccount
  name: icamklust
roleRef:
  kind: Role
  name: k8sdc-operator
  apiGroup: rbac.authorization.k8s.io
