apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: kubetoy-channel-deployment
  namespace: kubetoy-channel-namespace
  labels:
    app: kubetoy-app
spec:
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: kubetoy-channel-deployment
      labels:
        app: kubetoy-app
    spec:
        selector:
          matchLabels:
            app: kubetoy
        replicas: 1
        template:
          metadata:
            labels:
              app: kubetoy
          spec:
            containers:
            - name: kubetoy
              image: docker.io/ibmicpcoc/kubetoy:2.0.0
              imagePullPolicy: Always
              ports:
              - containerPort: 3000
              volumeMounts:
              - name: configvol
                mountPath: /var/config
              - name: secretvol
                mountPath: /var/secret
              livenessProbe:
                httpGet:
                  path: /health
                  port: 3000
                initialDelaySeconds: 10
                periodSeconds: 5
              env:
              - name: ENV_TOY_CONFIGMAP
                valueFrom: 
                  configMapKeyRef:
                    name: kubetoy-configmap-env
                    key: ENV_TOY_CONFIGMAP
              - name: ENV_TOY_SECRET
                valueFrom:
                  secretKeyRef:
                    name: kubetoy-secret-env
                    key: ENV_TOY_SECRET
            volumes:
            - name: configvol
              configMap:
                name: kubetoy-configmap-files
            - name: secretvol
              secret:
                secretName: kubetoy-secret-files
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: kubetoy-channel-service
  namespace:  kubetoy-channel-namespace
  labels:
    app: kubetoy-app
spec:
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: kubetoy-service
      labels:
        app: kubetoy-app
    spec:
      type: ClusterIP
      ports:
        - targetPort: 3000
          port: 3000
          protocol: TCP
          name: "http"
      selector:
        app: kubetoy
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: kubetoy-channel-route
  namespace: kubetoy-channel-namespace
  labels:
    app: kubetoy-app
spec:
  template:
    kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: kubetoy
      labels:
        app: kubetoy-app
    spec:
      subdomain: ''
      to:
        kind: Service
        name: kubetoy-service
        weight: 100
      port:
        targetPort: http
      wildcardPolicy: None
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: kubetoy-channel-cm-env
  namespace: kubetoy-channel-namespace
  labels:
    app: kubetoy-app
spec:
  template:
    spec: {}
    kind: ConfigMap
    apiVersion: v1
    metadata:
      name: kubetoy-configmap-env
    data:
      ENV_TOY_CONFIGMAP: 'This is a configuration value.'
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: kubetoy-channel-sec-env
  namespace: kubetoy-channel-namespace
  labels:
    app: kubetoy-app
spec:
  template:
    spec: {}
    apiVersion: v1
    kind: Secret
    metadata:
      name: kubetoy-secret-env
    type: Opaque
    data:
      ENV_TOY_SECRET: VGhpcyBpcyBhIHRlc3Q=
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: kubetoy-channel-cm-file
  namespace: kubetoy-channel-namespace
  labels:
    app: kubetoy-app
spec:
  template:
    spec: {}
    kind: ConfigMap
    apiVersion: v1
    metadata:
      name: kubetoy-configmap-files
    data:
      config.json: '{ "default": "123" }'
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: kubetoy-channel-sec-file
  namespace: kubetoy-channel-namespace
  labels:
    app: kubetoy-app
spec:
  template:
    spec: {}
    apiVersion: v1
    kind: Secret
    metadata:
      name: kubetoy-secret-files
    type: Opaque
    data:
      toy-secret.txt: U2hoLi4uIFRoaXMgaXMgYSBzZWNyZXQu


kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kubetoy
  labels:
    app: kubetoy-app
spec:
  subdomain: ''
  to:
    kind: Service
    name: kubetoy-service
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None