apiVersion: manageiq.org/v1alpha1
kind: ManageIQ
metadata:
  name: miq
spec:
  applicationDomain: MIQ_URL
  oidcCaCertSecret: miq-secret
  httpdAuthenticationType: openid-connect
  #deployMessagingService: true
  #httpdAuthConfig: miq-configuration
  initialAdminGroupName: demo
  oidcAuthIntrospectionURL: MCM_SERVER/idprovider/v1/auth/introspect
  oidcCaCertSecret: miq-secret
  oidcClientSecret: miq-client-secret
  oidcProviderURL: MCM_SERVER/idprovider/v1/auth/authorize