apiVersion: manageiq.org/v1alpha1
kind: ManageIQ
metadata:
  name: miq
spec:
  applicationDomain: MIQ_URL
  oidcCaCertSecret: miq-secret
  httpdAuthenticationType: openid-connect
  #deployMessagingService: true
  httpdAuthConfig: miq-configuration
  initialAdminGroupName: demo

