
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: grpcdemo-app
  namespace: grpcdemo-app
  generation: 1
  labels:
    app: grpcdemo-app
spec:
  componentKinds:
    - group: app.ibm.com
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - grpcdemo-app-web
          - grpcdemo-app-api
          - grpcdemo-app-server
