kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-infra-management-install-operator
  labels:
    app.kubernetes.io/name: ibm-infra-management-install-operator
    app.kubernetes.io/instance: ibm-infra-management-install-operator
    app.kubernetes.io/managed-by: ibm-infra-management-install-operator
subjects:
- kind: ServiceAccount
  name: ibm-infra-management-install-operator
  namespace: REPLACE_NAMESPACE
roleRef:
  kind: Role
  name: ibm-infra-management-install-operator
  apiGroup: rbac.authorization.k8s.io
