apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ibm-infra-management-install-operator
  labels:
    app.kubernetes.io/name: ibm-infra-management-install-operator
    app.kubernetes.io/instance: ibm-infra-management-install-operator
    app.kubernetes.io/managed-by: ibm-infra-management-install-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/finalizers
  - services
  - services/finalizers
  - persistentvolumeclaims
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - deployments
  - deployments/scale
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - rolebindings
  - roles
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - ibm-infra-management-install-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - infra.management.ibm.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes/custom-host
  verbs:
  - '*'
