
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: modresort-app
  namespace: modresort-app
  generation: 1
  labels:
    app: modresort-app
spec:
  componentKinds:
    - group: app.ibm.com
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - modresort-app-web
