kind: Secret
apiVersion: v1
metadata:
  name: my-oidc-secret
stringData:
  clientid: CLIENT_ID
  clientsecret: CLIENT_SECRET
  oidc.conf: |-
    LoadModule auth_openidc_module modules/mod_auth_openidc.so
    ServerName MIQ_URL
    LogLevel debug

    OIDCCLientID CLIENT_ID
    OIDCClientSecret CLIENT_SECRET
    OIDCRedirectURI https://MIQ_URL/oidc_login/redirect_uri
    OIDCCryptoPassphrase MCM_PASSWORD
    OIDCOAuthRemoteUserClaim sub
    OIDCRemoteUserClaim name

    # OIDCProviderMetadataURL missing
    OIDCProviderIssuer https://127.0.0.1:443/idauth/oidc/endpoint/OP
    OIDCProviderAuthorizationEndpoint MCM_SERVER/idprovider/v1/auth/authorize
    OIDCProviderTokenEndpoint MCM_SERVER/idprovider/v1/auth/token

    OIDCOAuthCLientID CLIENT_ID
    OIDCOAuthClientSecret CLIENT_SECRET
    OIDCOAuthIntrospectionEndpoint MCM_SERVER/idprovider/v1/auth/introspect

    OIDCProviderJwksUri MCM_SERVER/oidc/endpoint/OP/jwk
    OIDCProviderEndSessionEndpoint MCM_SERVER/idprovider/v1/auth/logout
    OIDCScope "openid email profile"
    OIDCResponseMode "query"
    OIDCProviderTokenEndpointAuth client_secret_post
    OIDCOAuthIntrospectionEndpointAuth client_secret_basic
    OIDCPassUserInfoAs json
    OIDCHTTPTimeoutShort 10
    OIDCCacheEncrypt On

    <Location /oidc_login>
      AuthType openid-connect
      Require valid-user
      LogLevel debug
    </Location>

    OIDCSSLValidateServer Off
    OIDCOAuthSSLValidateServer Off


    RequestHeader unset X_REMOTE_USER
    RequestHeader set X_REMOTE_USER  %{OIDC_CLAIM_PREFERRED_USERNAME}e env=OIDC_CLAIM_PREFERRED_USERNAME
    RequestHeader set X_EXTERNAL_AUTH_ERROR %{EXTERNAL_AUTH_ERROR}e env=EXTERNAL_AUTH_ERROR
    RequestHeader set X_REMOTE_USER_EMAIL %{OIDC_CLAIM_EMAIL}e env=OIDC_CLAIM_EMAIL
    RequestHeader set X_REMOTE_USER_FIRSTNAME %{OIDC_CLAIM_GIVEN_NAME}e env=OIDC_CLAIM_GIVEN_NAME
    RequestHeader set X_REMOTE_USER_LASTNAME %{OIDC_CLAIM_FAMILY_NAME}e env=OIDC_CLAIM_FAMILY_NAME
    RequestHeader set X_REMOTE_USER_FULLNAME  %{OIDC_CLAIM_NAME}e env=OIDC_CLAIM_NAME
    RequestHeader set X_REMOTE_USER_GROUPS %{OIDC_CLAIM_GROUPS}e env=OIDC_CLAIM_GROUPS
    RequestHeader set X_REMOTE_USER_DOMAIN %{OIDC_CLAIM_DOMAIN}e env=OIDC_CLAIM_DOMAIN