apiVersion: operator.openshift.io/v1
kind: ServiceCatalogAPIServer
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  generation: 1
  name: cluster
spec:
  logLevel: Normal
  managementState: Managed