apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: policy-rhocp-sdn
  namespace: default
  annotations:
    policy.mcm.ibm.com/categories: PROD SystemAndCommunicationsProtections
    policy.mcm.ibm.com/standards: FISMA
spec:
  complianceType: musthave
  disabled: false
  namespaces:
    exclude:
      - kube-*
    include:
      - openshift-sdn
  object-templates:
    - complianceType: musthave
      objectDefinition:
        kind: DaemonSet
        apiVersion: apps/v1
        metadata:
          name: ovs
          namespace: openshift-sdn
          labels:
            app: ovs
            component: network
            openshift.io/component: network
            type: infra
        spec:
          selector:
            matchLabels:
              app: ovs
          template:
            metadata:
              labels:
                app: ovs
                component: network
                openshift.io/component: network
                type: infra
              annotations:
                scheduler.alpha.kubernetes.io/critical-pod: ''
            spec:
              restartPolicy: Always
              serviceAccountName: sdn
              hostPID: true
              schedulerName: default-scheduler
              hostNetwork: true
              terminationGracePeriodSeconds: 30
              securityContext: {}
              containers:
                - resources:
                    requests:
                      cpu: 100m
                      memory: 300Mi
                  terminationMessagePath: /dev/termination-log
                  name: openvswitch
                  command:
                    - /bin/bash
                    - '-c'
                    - >
                      #!/bin/bash
        
                      set -euo pipefail
        
        
                      # cleanup old log files
        
                      rm -f /var/log/openvswitch-old/ovsdb-server.log
                      /var/log/openvswitch-old/ovs-vswitchd.log
        
        
                      mkdir -p /var/log/openvswitch
        
        
                      # if another process is listening on the cni-server socket, wait
                      until it exits
        
                      trap 'kill $(jobs -p); exit 0' TERM
        
                      retries=0
        
                      while true; do
                        if /usr/share/openvswitch/scripts/ovs-ctl status &>/dev/null; then
                          echo "warning: Another process is currently managing OVS, waiting 15s ..." 2>&1
                          sleep 15 & wait
                          (( retries += 1 ))
                        else
                          break
                        fi
                        if [[ "${retries}" -gt 40 ]]; then
                          echo "error: Another process is currently managing OVS, exiting" 2>&1
                          exit 1
                        fi
                      done
        
        
                      # launch OVS
        
                      function quit {
                          /usr/share/openvswitch/scripts/ovs-ctl stop
                          exit 0
                      }
        
                      trap quit SIGTERM
        
                      /usr/share/openvswitch/scripts/ovs-ctl start --no-ovs-vswitchd
                      --system-id=random
        
        
                      # Restrict the number of pthreads ovs-vswitchd creates to reduce
                      the
        
                      # amount of RSS it uses on hosts with many cores
        
                      # https://bugzilla.redhat.com/show_bug.cgi?id=1571379
        
                      # https://bugzilla.redhat.com/show_bug.cgi?id=1572797
        
                      if [[ `nproc` -gt 12 ]]; then
                          ovs-vsctl --no-wait set Open_vSwitch . other_config:n-revalidator-threads=4
                          ovs-vsctl --no-wait set Open_vSwitch . other_config:n-handler-threads=10
                      fi
        
                      /usr/share/openvswitch/scripts/ovs-ctl start --no-ovsdb-server
                      --system-id=random
        
        
                      tail --follow=name /var/log/openvswitch/ovs-vswitchd.log
                      /var/log/openvswitch/ovsdb-server.log &
        
                      sleep 20
        
                      while true; do
                        if ! /usr/share/openvswitch/scripts/ovs-ctl status &>/dev/null; then
                          echo "OVS seems to have crashed, exiting"
                          quit
                        fi
                        sleep 15
                      done
                  livenessProbe:
                    exec:
                      command:
                        - /usr/share/openvswitch/scripts/ovs-ctl
                        - status
                    initialDelaySeconds: 15
                    timeoutSeconds: 1
                    periodSeconds: 5
                    successThreshold: 1
                    failureThreshold: 3
                  securityContext:
                    privileged: true
                    runAsUser: 0
                  imagePullPolicy: IfNotPresent
                  volumeMounts:
                    - name: host-modules
                      readOnly: true
                      mountPath: /lib/modules
                    - name: host-run-ovs
                      mountPath: /run/openvswitch
                    - name: host-run-ovs
                      mountPath: /var/run/openvswitch
                    - name: host-sys
                      readOnly: true
                      mountPath: /sys
                    - name: host-config-openvswitch
                      mountPath: /etc/openvswitch
                    - name: log-openvswitch
                      mountPath: /var/log/openvswitch-old
                  terminationMessagePolicy: File
                  image: 'docker.io/openshift/origin-node:v3.11'
              serviceAccount: sdn
              volumes:
                - name: host-modules
                  hostPath:
                    path: /lib/modules
                    type: ''
                - name: host-run-ovs
                  hostPath:
                    path: /run/openvswitch
                    type: ''
                - name: host-sys
                  hostPath:
                    path: /sys
                    type: ''
                - name: host-config-openvswitch
                  hostPath:
                    path: /etc/origin/openvswitch
                    type: ''
                - name: log-openvswitch
                  hostPath:
                    path: /var/log/openvswitch
                    type: DirectoryOrCreate
              dnsPolicy: ClusterFirst
              tolerations:
                - operator: Exists
              priorityClassName: system-node-critical
          updateStrategy:
            type: OnDelete
          revisionHistoryLimit: 10
  remediationAction: inform
  severity: high
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: binding-policy-rhocp-sdn
  namespace: default
  labels:
    name: binding-policy-rhocp-sdn
    placementPolicy: placement-policy-rhocp-sdn
placementRef:
  name: placement-policy-rhocp-sdn
  apiGroup: mcm.ibm.com
  kind: PlacementPolicy
subjects:
  - name: policy-rhocp-sdn
    apiGroup: policy.mcm.ibm.com
    kind: Policy
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: placement-policy-rhocp-sdn
  namespace: default
spec:
  clusterLabels:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - RHOCP
      - key: cloud
        operator: In
        values:
          - DC-EU-West-1
  resourceHint: {}
  resourceSelector: {}
